### ISSUE TITLE
[Feature]: Display app version in App information

### ISSUE THREAD

**Issue by Mitia99** [AwaitQuality/windowsonarm#49]
**What feature would you like to be added**

It will be great to have the app version displayed in **App information** like on [worksonwoa](https://www.worksonwoa.com/applications/) website

Thanks for considering this,

**Comment by OpenSource03** [comment]
Thank you for your request.

This seems like too much, it will make it harder for contributors, and as I can already see most of them will not even be willing to search for app version, it will end up on us reviewers to find it and it will just be too much work overall...

At the end, we have "beta support", or "native" status. If it's in beta support, users clearly know that they need a beta version in order to download the app. If it's native, they know that they just need to update to the latest version and it will be native.

**Comment by Mitia99** [comment]
@OpenSource03 

>At the end, we have "beta support", or "native" status. If it's in beta support, users clearly know that they need a beta version in order to download the app. If it's native, they know that they just need to update to the latest version and it will be native.

Well, rather than **beta** or **native** status, the app version concerns **Emulated** and **Not supported** status.

The thing is that there are cases where old versions work emulated and newer ones don't.

Having the app version displayed will definitely help users download the working version as a workaround until a beta or stable ARM version is released.

>This seems like too much, it will make it harder for contributors, and as I can already see most of them will not even be willing to search for app version, it will end up on us reviewers to find it and it will just be too much work overall...

It doesn't need to be perfect though. I mean, you can simply leave a `App version: N/A` like this

![image](https://github.com/user-attachments/assets/5a50b5b7-e71a-4569-8793-853899b14dad)

In this regard, contributors who are willing to will add a version and others won't.
